# Generated by Django 4.0.5 on 2022-06-27 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20220625_1631'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('text',)},
        ),
    ]
